name: movabletype/mt-chart-api-sdk-js
on:
  push:
    branches:
    - "**/*"
  pull_request:
  schedule:
  - cron: 31 22 6 * *
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  test:
    runs-on: # this agent type is not supported: [[{"dist"=>"jammy"}]]
             ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-node@v4.0.0
      with:
        cache: npm
        node-version: 22
    - run: npm install
    - run: npm install -g grunt-cli
    - run: grunt build
